name: CI

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 checks:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
   - run: yarn --frozen-lockfile
   - run: yarn checks
   - run: yarn test
   - run: yarn build
